// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package audoctl

import (
	"github.com/audoctl/audoctl/configs"
	"github.com/audoctl/audoctl/internal/audoctl/modules/event"
	"github.com/audoctl/audoctl/internal/audoctl/modules/session"
	"github.com/audoctl/audoctl/internal/audoctl/modules/timeline"
	"github.com/rs/zerolog"
	"gorm.io/gorm"
)

// Injectors from wire.go:

func InitHandlers(db *gorm.DB, cfg *configs.Config, logger zerolog.Logger) Handlers {
	repository := event.NewRepository(db)
	service := event.NewService(repository)
	handler := event.NewHandler(service)
	timelineRepository := timeline.NewRepository(db)
	timelineService := timeline.NewService(timelineRepository)
	timelineHandler := timeline.NewHandler(timelineService)
	sessionRepository := session.NewRepository(db)
	sessionService := session.NewService(sessionRepository)
	sessionHandler := session.NewHandler(sessionService)
	handlers := Handlers{
		Event:    handler,
		Timeline: timelineHandler,
		Session:  sessionHandler,
	}
	return handlers
}
